version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: attendance_db
    environment:
      POSTGRES_USER: attendance_user
      POSTGRES_PASSWORD: attendance_pass
      POSTGRES_DB: attendance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U attendance_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: attendance_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance_api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: attendance_user
      DB_PASSWORD: attendance_pass
      DB_NAME: attendance_db
      JWT_SECRET: your-secret-key-change-in-production
      PORT: 8080
      REDIS_ADDR: redis:6379
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
  redis_data:
